INSERT INTO forbidden_words (word) VALUES
                                       ('stupid'),
                                       ('idiot'),
                                       ('dumb'),
                                       ('moron'),
                                       ('fool'),
                                       ('loser'),
                                       ('jerk'),
                                       ('scammer'),
                                       ('fraud'),
                                       ('liar'),
                                       ('cheater'),
                                       ('thief'),
                                       ('coward'),
                                       ('bitch'),
                                       ('motherfucker'),
                                       ('arrogant'),
                                       ('selfish'),
                                       ('rude'),
                                       ('annoying'),
                                       ('useless'),
                                       ('worthless'),
                                       ('pathetic'),
                                       ('fuck');

